- block:
    - name: setup fact with zones loaded from host variables
      include_role:
        name: amtega.select_hostvars
        apply:
          tags:
            - role::rsyslog
            - role::rsyslog::configure
      vars:
        select_hostvars_pattern: "^rsyslog_modules_.*"
        select_hostvars_fact_name: rsyslog_hostvars_modules
        select_hostvars_output_type: list

    - name: setup fact with zones that will be managed
      set_fact:
        rsyslog_modules_managed: >-
          {{ (syslog_load_modules_from_hostvars
              and not rsyslog_hostvars_modules is string)
              | ternary([ rsyslog_hostvars_modules ] | flatten
                        + rsyslog_modules,
                        rsyslog_modules) }}

    - name: deploy config files for rsyslog output modules
      template:
        src: configure.yml
        dest: "{{ rsyslog_config_dir }}"/"{{ module.filename }}
      loop: "{{ rsyslog_modules_managed }}"
      loop_control:
        loop_var: module
      notify: rsyslog service restart
  tags:
    - role::rsyslog
    - role::rsyslog::configure
