---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 27
      rhel: 6

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        6:
          rsyslog: absent
      rhel:
        6:
          rsyslog: absent

- include_role:
    name: amtega.packages
  vars:
    packages_os: "{{ rsyslog_packages_os }}"

- include_role:
    name: amtega.select_hostvars
  vars:
    select_hostvars_query:
      pattern: "^rsyslog_modules_.*"
      fact_name: rsyslog_modules_hostvars
      output_type: list

- block:
    - name: Setup config files for rsyslog output modules
      template:
        src: module.j2
        dest: "{{ rsyslog_config_dir }}/{{ rsyslog_module.filename }}"
      loop: "{{ rsyslog_modules_to_manage }}"
      loop_control:
        loop_var: rsyslog_module
        label: "{{ rsyslog_config_dir }}/{{ rsyslog_module.filename }}"
      notify: rsyslog service restart
      vars:
        rsyslog_modules_to_manage: >-
          {{ rsyslog_modules
             + ((rsyslog_load_from_hostvars)
                | ternary(rsyslog_modules_hostvars
                          | default([])
                          | flatten,
                          [])) }}

    - name: Setup rsyslog options
      lineinfile:
        path: "{{ rsyslog_sysconfig_file }}"
        regexp: '^SYSLOGD_OPTIONS='
        line: 'SYSLOGD_OPTIONS="{{ rsyslog_options }}"'
      notify: rsyslog service restart
  tags:
    - role::rsyslog
    - role::rsyslog::configure
