---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - amtega.rsyslog
  tasks:
    - name: Check rsyslog configuration
      command: rsyslogd -N 1 -f "{{ rsyslog_config_file }}"
      register: rsyslog_check
      changed_when: no
      failed_when: >-
        not rsyslog_check.stderr is search("End of config validation run")
