---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check rsyslog configuration
      command: rsyslogd -N 1 -f /etc/rsyslog.conf
      register: rsyslog_check
      changed_when: no
      failed_when: >-
        not rsyslog_check.stderr is search("End of config validation run")
